language: python
sudo: false
python:
    - "2.7"
    - "3.4"
    - "3.5"
install:
    - pip install -qU pip wheel
    - pip install -q -U -r requirements_test.txt
script:
    - flake8 django_cockatiel tests
    - cd tests
    - python run_integration_tests.py
cache:
    directories:
        - $HOME/.cache/pip
